[package]
name = "hollow"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
# scraper = "0.21.0"
select = "0.6.0"
error-chain = "0.12.4"
tokio = { version = "1.41.1", features = ["full"] }
